services:
  - type: web
    name: medivoice
    env: python
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: WHISPER_MODEL
        value: base
      - key: WHISPER_DEVICE
        value: cpu
      - key: WHISPER_COMPUTE_TYPE
        value: int8
      - key: PYTHONUNBUFFERED
        value: "1"
    aptPackages:
      - ffmpeg
